### ISSUE TITLE
modules missing

### ISSUE THREAD

**Issue by geochri** [LuyenKhacBui/ISCE2GIAnT#1]
How can we fix this issue on the second script (topsApp_inTurn_2_choose_IFG.py)?

from modules.geotools import DecimalYearComp as decyrcomp
ModuleNotFoundError: No module named 'modules'

Thanks

**Comment by LuyenKhacBui** [comment]
Hi @geochri,
Thanks for catching this up. This relates to a function located in a local module. For convenience, I have added the function directly to the script and commented out the line calling the function from its module. Now, this should work.
Please let me know if any other issues.
Luyen

**Comment by geochri** [comment]
Thank you @LuyenKhacBui.
I can confirm that the script for this step is working now.
